### ISSUE TITLE
Remove import tables

### ISSUE THREAD

**Issue by jacebenson** [jnerius/sn-slack-points-thing#20]
Before anyone starts on this can we get a yay or nay? @jnerius Thanks

I'm suggesting reducing the size of the application initially to get rid of some of extra stuff.

By removing the x_snc_slack_points_import things we'll remove 9 things that were only used for an initial import.  
5 Dictionary records, 4 labels.
It seems at least the 5 dictionary records get a new sys_id on each install.

**Comment by jacebenson** [comment]
Also this I believe would also remove 4 role records.

**Comment by jnerius** [comment]
There are a few reasons I'd like the import tables to stick around: 
- When starting this app in a new instance, someone may want to import ++ from chat history. 
- With planned changes to the point data model, we will need to re-import from history at some date in the future.

**Comment by jacebenson** [comment]
Okay I'll close this.  I just thought cleaning up the repo would be nice for seeing teh diffs since it seems on every pull request this is responsible for 14 updates that aren't actually updates.
