### ISSUE TITLE
Remove second unused point table

### ISSUE THREAD

**Issue by jacebenson** [jnerius/sn-slack-points-thing#21]
Before anyone starts on this can we get a yay or nay? @jnerius Thanks

I'm suggesting reducing the size of the application initially to get rid of some of extra stuff.

By removing the x_snc_slack_points_point things we'll remove 11 things that are currently not used.
5 Dictionary records, 5 labels, 1 list record
It seems at least the 5 dictionary records get a new sys_id on each install

**Comment by jacebenson** [comment]
Also this I believe would also remove 4 role records.

**Comment by jnerius** [comment]
This table will actually be used as we enhance the point tracking model. Currently, we only track a simple numeric value against a user record. The second points table will track individual points, including: 

 - Who gave them out
 - Who received them
 - Which channel they were on
 - Which thread they were on
 - Type of point (other than ++) 

I'll add some issues to the repo that align with the design I was working on.

**Comment by jacebenson** [comment]
Okay I'll close this. I just thought cleaning up the repo would be nice for seeing teh diffs since it seems on every pull request this is responsible for 14 updates that aren't actually updates.
